
kind: Namespace
apiVersion: v1
metadata:
  name: traefik-golang
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-golang
  labels:
    app: traefik-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-golang
  template:
    metadata:
      labels:
        app: traefik-golang
    spec:
      containers:
      - name: traefik-golang
        image: tftest/traefik-golang
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-golang
spec:
  selector:
    app: traefik-golang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
